-- UTF-8 / PostgreSQL 15+
-- 서버 코드베이스·시드 검증 데이터는 SQLite가 아닌 PostgreSQL 원장을 사용한다.

CREATE TABLE IF NOT EXISTS codebases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    prompt TEXT NOT NULL,
    code TEXT NOT NULL,
    mode TEXT,
    tags JSONB NOT NULL DEFAULT '[]'::jsonb,
    difficulty INTEGER,
    tier INTEGER,
    solves_count INTEGER,
    strategy_level INTEGER,
    branch_conditions INTEGER,
    validated_seeds JSONB NOT NULL DEFAULT '[]'::jsonb,
    tier_source TEXT,
    quality_status TEXT NOT NULL DEFAULT 'pending_validation',
    quality_reasons JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS codebase_seed_cache (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codebase_id BIGINT NOT NULL,
    code_hash TEXT NOT NULL,
    seed BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (codebase_id, code_hash, seed)
);

CREATE TABLE IF NOT EXISTS codebase_seed_stats (
    codebase_id BIGINT NOT NULL,
    code_hash TEXT NOT NULL,
    attempts BIGINT NOT NULL DEFAULT 0,
    successes BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (codebase_id, code_hash)
);

CREATE TABLE IF NOT EXISTS codebase_seed_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codebase_id BIGINT NOT NULL,
    code_hash TEXT NOT NULL,
    seed BIGINT,
    status TEXT NOT NULL,
    error_type TEXT,
    error_message TEXT,
    stage TEXT,
    elapsed_ms INTEGER,
    source TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS codebase_agent_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codebase_id BIGINT,
    action TEXT NOT NULL,
    status TEXT NOT NULL,
    attempt INTEGER,
    error_message TEXT,
    detail JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS codebase_quality_validation (
    codebase_id BIGINT NOT NULL,
    code_hash TEXT NOT NULL,
    seed BIGINT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('approved', 'rejected')),
    reasons_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    checked_at BIGINT NOT NULL,
    PRIMARY KEY (codebase_id, code_hash, seed)
);

CREATE TABLE IF NOT EXISTS formula_seed_cache (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    signature TEXT NOT NULL,
    seed BIGINT NOT NULL,
    params_json JSONB,
    answers_json JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (signature, seed)
);

CREATE INDEX IF NOT EXISTS idx_codebases_student_ready
    ON codebases (tier, id) WHERE quality_status = 'approved';
CREATE INDEX IF NOT EXISTS idx_codebase_seed_cache_lookup
    ON codebase_seed_cache (codebase_id, code_hash);
CREATE INDEX IF NOT EXISTS idx_codebase_seed_logs_lookup
    ON codebase_seed_logs (codebase_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_codebase_agent_logs_lookup
    ON codebase_agent_logs (codebase_id, id DESC);
