Map<String, dynamic> buildCourseV2Payload({
  required String title,
  required String description,
  required bool advancedOpen,
  required String difficulty,
  required int targetOvr,
  required List<String> tags,
  required List<String> focusTags,
  String? textbookId,
  required List<Map<String, dynamic>> modules,
  required bool curriculumEnabled,
  required int curriculumEveryNDays,
  required int curriculumMaxDeadlineDeviation,
  required int curriculumDailyMaxModules,
  required List<int> moduleDeadlineDays,
  bool wrongAnswerReviewEnabled = true,
  bool isPublic = false,
}) {
  return <String, dynamic>{
    'title': title,
    'description': description,
    'difficulty': advancedOpen ? difficulty : '',
    'duration': '',
    'target_ovr': advancedOpen ? targetOvr : 0,
    'tags': tags,
    'focus_tags': focusTags,
    if ((textbookId ?? '').trim().isNotEmpty) 'textbook_id': textbookId,
    'textbook_pages': 0,
    'is_public': isPublic,
    'modules': modules,
    'runtime_flags': {
      'show_timer': true,
      'show_progress_bar': true,
      'force_answer_riddle': false,
      'enable_wrong_answer_auto_insert': wrongAnswerReviewEnabled,
      'enable_hints': true,
    },
    'curriculum_settings': {
      'enabled': curriculumEnabled,
      'every_n_days': curriculumEveryNDays,
      'max_deadline_deviation': curriculumMaxDeadlineDeviation,
      'daily_max_modules': curriculumDailyMaxModules,
      'module_deadline_days': moduleDeadlineDays,
    },
    'challenge_settings': {
      'enabled': true,
      'daily_random_count_min': 3,
      'daily_random_count_max': 5,
      'available_types': const [
        'course_stage_progress',
        'solve_n_problems',
        'exam_accuracy_threshold',
        'attendance_complete',
        'attendance_3day_streak',
        'activity_score_reach',
        'textbook_read_complete',
        'ask_friend_problem',
        'open_documents_box',
        'weakness_review_n_problems',
      ],
    },
  };
}
