"""Default daily quest templates.

These templates are seeded into SQLite so teachers can edit or disable them.
Daily quest assignment still reads from the DB first; this file is only the default
catalog for first run and recovery.
"""
from __future__ import annotations

from typing import Any


POINTS_BY_DIFFICULTY = {
    "easy": 10,
    "medium": 20,
    "hard": 40,
}


DAILY_DIFFICULTY_QUOTA = {
    "easy": 2,
    "medium": 2,
    "hard": 1,
}


DEFAULT_DAILY_CHALLENGE_TEMPLATES: list[dict[str, Any]] = [
    {
        "template_key": "easy_attendance_check",
        "difficulty": "easy",
        "title": "오늘 학습 출석 완료",
        "description": "코스에 접속해 오늘 학습을 시작합니다.",
        "quest_type": "attendance_complete",
        "target": 1,
        "module_types": ["textbook_view", "problem_solve", "exam_solve"],
    },
    {
        "template_key": "easy_solve_3",
        "difficulty": "easy",
        "title": "기본문제 3문항 풀기",
        "description": "코스 문제를 3문항 풉니다.",
        "quest_type": "solve_n_problems",
        "target": 3,
        "module_types": ["problem_solve", "challenge_group"],
    },
    {
        "template_key": "easy_solve_5",
        "difficulty": "easy",
        "title": "기본문제 5문항 풀기",
        "description": "코스 문제를 5문항 풉니다.",
        "quest_type": "solve_n_problems",
        "target": 5,
        "module_types": ["problem_solve", "challenge_group"],
    },
    {
        "template_key": "easy_textbook_open",
        "difficulty": "easy",
        "title": "교재 한 번 열기",
        "description": "오늘 배정된 교재를 열어 학습을 시작합니다.",
        "quest_type": "open_documents_box",
        "target": 1,
        "module_types": ["textbook_view"],
    },
    {
        "template_key": "easy_textbook_read",
        "difficulty": "easy",
        "title": "교재 한 단락 읽기",
        "description": "교재 학습 모듈을 1회 완료합니다.",
        "quest_type": "textbook_read_complete",
        "target": 1,
        "module_types": ["textbook_view"],
    },
    {
        "template_key": "easy_course_step",
        "difficulty": "easy",
        "title": "코스 단계 1개 진행",
        "description": "오늘 코스 모듈을 하나 진행합니다.",
        "quest_type": "course_stage_progress",
        "target": 1,
        "module_types": ["textbook_view", "problem_solve", "exam_solve"],
    },
    {
        "template_key": "easy_review_2",
        "difficulty": "easy",
        "title": "약점 복습 2문항",
        "description": "약점 복습 문제를 2문항 풉니다.",
        "quest_type": "weakness_review_n_problems",
        "target": 2,
        "module_types": ["wrong_answer_review"],
    },
    {
        "template_key": "easy_friend_ask",
        "difficulty": "easy",
        "title": "친구에게 문제 질문하기",
        "description": "모르는 문제를 친구에게 1회 질문합니다.",
        "quest_type": "ask_friend_problem",
        "target": 1,
        "module_types": ["problem_solve", "exam_solve"],
    },
    {
        "template_key": "easy_activity_30",
        "difficulty": "easy",
        "title": "활동 점수 30 달성",
        "description": "오늘 학습 활동 점수 30점을 달성합니다.",
        "quest_type": "activity_score_reach",
        "target": 30,
        "module_types": ["textbook_view", "problem_solve"],
    },
    {
        "template_key": "easy_exam_try",
        "difficulty": "easy",
        "title": "미니 테스트 1회 응시",
        "description": "코스 내 시험 또는 미니 테스트를 1회 응시합니다.",
        "quest_type": "exam_attempt",
        "target": 1,
        "module_types": ["exam_solve", "level_test"],
    },
    {
        "template_key": "easy_hint_review",
        "difficulty": "easy",
        "title": "힌트 확인 후 다시 풀기",
        "description": "힌트를 확인한 문제를 다시 1문항 풉니다.",
        "quest_type": "hint_retry",
        "target": 1,
        "module_types": ["problem_solve", "wrong_answer_review"],
    },
    {
        "template_key": "easy_wrong_note_open",
        "difficulty": "easy",
        "title": "오답노트 열기",
        "description": "오답노트를 열어 오늘 복습을 시작합니다.",
        "quest_type": "wrong_answer_open",
        "target": 1,
        "module_types": ["wrong_answer_review"],
    },
    {
        "template_key": "easy_formula_check",
        "difficulty": "easy",
        "title": "핵심 공식 확인",
        "description": "오늘 단원의 핵심 공식을 1회 확인합니다.",
        "quest_type": "formula_check",
        "target": 1,
        "module_types": ["textbook_view", "curriculum_group"],
    },
    {
        "template_key": "easy_timer_10",
        "difficulty": "easy",
        "title": "집중 학습 10분",
        "description": "학습 타이머로 10분 이상 집중합니다.",
        "quest_type": "focus_minutes",
        "target": 10,
        "module_types": ["textbook_view", "problem_solve"],
    },
    {
        "template_key": "easy_tag_review",
        "difficulty": "easy",
        "title": "오늘 태그 복습",
        "description": "오늘 코스 태그에 해당하는 내용을 1회 복습합니다.",
        "quest_type": "tag_review",
        "target": 1,
        "module_types": ["curriculum_group", "textbook_view"],
    },
    {
        "template_key": "easy_graph_open",
        "difficulty": "easy",
        "title": "그래프 도구 열기",
        "description": "그래프 도구를 열어 개념을 확인합니다.",
        "quest_type": "graph_tool_open",
        "target": 1,
        "module_types": ["textbook_view", "problem_solve"],
    },
    {
        "template_key": "easy_solution_read",
        "difficulty": "easy",
        "title": "풀이 1개 읽기",
        "description": "풀이를 1개 읽고 흐름을 확인합니다.",
        "quest_type": "solution_read",
        "target": 1,
        "module_types": ["problem_solve", "wrong_answer_review"],
    },
    {
        "template_key": "easy_daily_plan",
        "difficulty": "easy",
        "title": "오늘 학습 계획 확인",
        "description": "오늘 할 일을 확인하고 코스 학습을 시작합니다.",
        "quest_type": "daily_plan_check",
        "target": 1,
        "module_types": ["curriculum_group"],
    },
    {
        "template_key": "easy_level_view",
        "difficulty": "easy",
        "title": "레벨 현황 확인",
        "description": "내 레벨과 활동 점수를 확인합니다.",
        "quest_type": "level_status_view",
        "target": 1,
        "module_types": ["level_test", "challenge_group"],
    },
    {
        "template_key": "easy_finish_one",
        "difficulty": "easy",
        "title": "작은 목표 1개 끝내기",
        "description": "오늘 배정된 작은 목표를 1개 완료합니다.",
        "quest_type": "micro_goal_complete",
        "target": 1,
        "module_types": ["textbook_view", "problem_solve", "exam_solve"],
    },
    {
        "template_key": "medium_solve_8",
        "difficulty": "medium",
        "title": "문제 8문항 풀기",
        "description": "코스 문제를 8문항 풉니다.",
        "quest_type": "solve_n_problems",
        "target": 8,
        "module_types": ["problem_solve", "challenge_group"],
    },
    {
        "template_key": "medium_solve_10",
        "difficulty": "medium",
        "title": "문제 10문항 풀기",
        "description": "코스 문제를 10문항 풉니다.",
        "quest_type": "solve_n_problems",
        "target": 10,
        "module_types": ["problem_solve", "challenge_group"],
    },
    {
        "template_key": "medium_accuracy_70",
        "difficulty": "medium",
        "title": "정확도 70% 달성",
        "description": "오늘 풀이에서 정확도 70% 이상을 달성합니다.",
        "quest_type": "exam_accuracy_threshold",
        "target": 70,
        "module_types": ["problem_solve", "exam_solve"],
    },
    {
        "template_key": "medium_accuracy_80",
        "difficulty": "medium",
        "title": "정확도 80% 달성",
        "description": "오늘 풀이에서 정확도 80% 이상을 달성합니다.",
        "quest_type": "exam_accuracy_threshold",
        "target": 80,
        "module_types": ["problem_solve", "exam_solve"],
    },
    {
        "template_key": "medium_review_5",
        "difficulty": "medium",
        "title": "약점 복습 5문항",
        "description": "약점 복습 문제를 5문항 풉니다.",
        "quest_type": "weakness_review_n_problems",
        "target": 5,
        "module_types": ["wrong_answer_review"],
    },
    {
        "template_key": "medium_wrong_correct_3",
        "difficulty": "medium",
        "title": "오답 3개 바로잡기",
        "description": "오답 문제 3개를 다시 풀어 맞힙니다.",
        "quest_type": "wrong_answer_correct",
        "target": 3,
        "module_types": ["wrong_answer_review"],
    },
    {
        "template_key": "medium_textbook_2",
        "difficulty": "medium",
        "title": "교재 학습 2회 완료",
        "description": "교재 학습 모듈을 2회 완료합니다.",
        "quest_type": "textbook_read_complete",
        "target": 2,
        "module_types": ["textbook_view"],
    },
    {
        "template_key": "medium_course_2",
        "difficulty": "medium",
        "title": "코스 단계 2개 진행",
        "description": "오늘 코스 모듈을 2개 진행합니다.",
        "quest_type": "course_stage_progress",
        "target": 2,
        "module_types": ["textbook_view", "problem_solve", "exam_solve"],
    },
    {
        "template_key": "medium_exam_2",
        "difficulty": "medium",
        "title": "미니 테스트 2회 응시",
        "description": "코스 내 시험 또는 미니 테스트를 2회 응시합니다.",
        "quest_type": "exam_attempt",
        "target": 2,
        "module_types": ["exam_solve", "level_test"],
    },
    {
        "template_key": "medium_timer_25",
        "difficulty": "medium",
        "title": "집중 학습 25분",
        "description": "학습 타이머로 25분 이상 집중합니다.",
        "quest_type": "focus_minutes",
        "target": 25,
        "module_types": ["textbook_view", "problem_solve"],
    },
    {
        "template_key": "medium_activity_60",
        "difficulty": "medium",
        "title": "활동 점수 60 달성",
        "description": "오늘 학습 활동 점수 60점을 달성합니다.",
        "quest_type": "activity_score_reach",
        "target": 60,
        "module_types": ["textbook_view", "problem_solve"],
    },
    {
        "template_key": "medium_streak_3",
        "difficulty": "medium",
        "title": "3일 연속 출석 유지",
        "description": "학습 출석 3일 연속 기록을 유지합니다.",
        "quest_type": "attendance_3day_streak",
        "target": 3,
        "module_types": ["textbook_view", "problem_solve"],
    },
    {
        "template_key": "medium_graph_practice",
        "difficulty": "medium",
        "title": "그래프 문제 2개 분석",
        "description": "그래프 도구를 활용해 문제 2개를 분석합니다.",
        "quest_type": "graph_problem_analyze",
        "target": 2,
        "module_types": ["problem_solve", "exam_solve"],
    },
    {
        "template_key": "medium_friend_help",
        "difficulty": "medium",
        "title": "친구 풀이 도움 1회",
        "description": "친구의 질문에 풀이 도움을 1회 제공합니다.",
        "quest_type": "friend_help_answer",
        "target": 1,
        "module_types": ["problem_solve"],
    },
    {
        "template_key": "medium_solution_compare",
        "difficulty": "medium",
        "title": "내 풀이와 해설 비교",
        "description": "해설과 내 풀이를 비교해 2문항을 점검합니다.",
        "quest_type": "solution_compare",
        "target": 2,
        "module_types": ["problem_solve", "wrong_answer_review"],
    },
    {
        "template_key": "medium_formula_apply",
        "difficulty": "medium",
        "title": "공식 적용 3문항",
        "description": "핵심 공식을 적용하는 문제 3문항을 풉니다.",
        "quest_type": "formula_apply",
        "target": 3,
        "module_types": ["problem_solve"],
    },
    {
        "template_key": "medium_tag_mastery",
        "difficulty": "medium",
        "title": "코스 태그 2개 복습",
        "description": "오늘 코스 태그 2개를 복습합니다.",
        "quest_type": "tag_review",
        "target": 2,
        "module_types": ["curriculum_group", "textbook_view"],
    },
    {
        "template_key": "medium_level_checkpoint",
        "difficulty": "medium",
        "title": "레벨 체크 1회",
        "description": "레벨 테스트 또는 체크포인트를 1회 완료합니다.",
        "quest_type": "level_checkpoint",
        "target": 1,
        "module_types": ["level_test"],
    },
    {
        "template_key": "medium_retry_until_correct",
        "difficulty": "medium",
        "title": "재도전으로 3문항 정답",
        "description": "틀린 문제를 재도전해 3문항을 맞힙니다.",
        "quest_type": "retry_correct",
        "target": 3,
        "module_types": ["wrong_answer_review", "problem_solve"],
    },
    {
        "template_key": "medium_complete_bundle",
        "difficulty": "medium",
        "title": "오늘 묶음 학습 완료",
        "description": "오늘 배정된 학습 묶음 1개를 끝냅니다.",
        "quest_type": "bundle_complete",
        "target": 1,
        "module_types": ["curriculum_group", "challenge_group"],
    },
    {
        "template_key": "hard_solve_15",
        "difficulty": "hard",
        "title": "고난도 포함 15문항 풀기",
        "description": "오늘 코스 문제를 15문항 풉니다.",
        "quest_type": "solve_n_problems",
        "target": 15,
        "module_types": ["problem_solve", "challenge_group"],
    },
    {
        "template_key": "hard_accuracy_90",
        "difficulty": "hard",
        "title": "정확도 90% 달성",
        "description": "오늘 풀이 또는 시험에서 정확도 90% 이상을 달성합니다.",
        "quest_type": "exam_accuracy_threshold",
        "target": 90,
        "module_types": ["problem_solve", "exam_solve"],
    },
    {
        "template_key": "hard_exam_perfect",
        "difficulty": "hard",
        "title": "미니 테스트 만점",
        "description": "미니 테스트 1회에서 만점을 달성합니다.",
        "quest_type": "exam_perfect_score",
        "target": 1,
        "module_types": ["exam_solve", "level_test"],
    },
    {
        "template_key": "hard_wrong_clear_8",
        "difficulty": "hard",
        "title": "오답 8개 정리",
        "description": "오답 문제 8개를 다시 풀고 정리합니다.",
        "quest_type": "wrong_answer_correct",
        "target": 8,
        "module_types": ["wrong_answer_review"],
    },
    {
        "template_key": "hard_review_10",
        "difficulty": "hard",
        "title": "약점 복습 10문항",
        "description": "약점 복습 문제를 10문항 풉니다.",
        "quest_type": "weakness_review_n_problems",
        "target": 10,
        "module_types": ["wrong_answer_review"],
    },
    {
        "template_key": "hard_course_3",
        "difficulty": "hard",
        "title": "코스 단계 3개 진행",
        "description": "오늘 코스 모듈을 3개 진행합니다.",
        "quest_type": "course_stage_progress",
        "target": 3,
        "module_types": ["textbook_view", "problem_solve", "exam_solve"],
    },
    {
        "template_key": "hard_timer_45",
        "difficulty": "hard",
        "title": "집중 학습 45분",
        "description": "학습 타이머로 45분 이상 집중합니다.",
        "quest_type": "focus_minutes",
        "target": 45,
        "module_types": ["textbook_view", "problem_solve"],
    },
    {
        "template_key": "hard_activity_100",
        "difficulty": "hard",
        "title": "활동 점수 100 달성",
        "description": "오늘 학습 활동 점수 100점을 달성합니다.",
        "quest_type": "activity_score_reach",
        "target": 100,
        "module_types": ["textbook_view", "problem_solve", "exam_solve"],
    },
    {
        "template_key": "hard_no_hint_5",
        "difficulty": "hard",
        "title": "힌트 없이 5문항 정답",
        "description": "힌트를 보지 않고 5문항을 맞힙니다.",
        "quest_type": "no_hint_correct",
        "target": 5,
        "module_types": ["problem_solve", "exam_solve"],
    },
    {
        "template_key": "hard_speed_solve",
        "difficulty": "hard",
        "title": "제한시간 안에 7문항",
        "description": "제한시간 안에 문제 7문항을 풉니다.",
        "quest_type": "timed_solve",
        "target": 7,
        "module_types": ["problem_solve", "exam_solve"],
    },
    {
        "template_key": "hard_graph_master",
        "difficulty": "hard",
        "title": "그래프 해석 5문항",
        "description": "그래프가 포함된 문제 5문항을 분석합니다.",
        "quest_type": "graph_problem_analyze",
        "target": 5,
        "module_types": ["problem_solve", "exam_solve"],
    },
    {
        "template_key": "hard_explain_solution",
        "difficulty": "hard",
        "title": "풀이 설명 2회 작성",
        "description": "문제 풀이 설명을 2회 작성합니다.",
        "quest_type": "solution_explain",
        "target": 2,
        "module_types": ["problem_solve", "wrong_answer_review"],
    },
    {
        "template_key": "hard_friend_teach",
        "difficulty": "hard",
        "title": "친구에게 개념 설명",
        "description": "친구에게 오늘 배운 개념을 1회 설명합니다.",
        "quest_type": "friend_help_answer",
        "target": 1,
        "module_types": ["textbook_view", "problem_solve"],
    },
    {
        "template_key": "hard_level_up",
        "difficulty": "hard",
        "title": "레벨 상승 도전",
        "description": "레벨 체크를 통과해 성장 조건을 달성합니다.",
        "quest_type": "level_checkpoint",
        "target": 1,
        "module_types": ["level_test"],
    },
    {
        "template_key": "hard_tag_mastery_3",
        "difficulty": "hard",
        "title": "코스 태그 3개 마스터",
        "description": "오늘 코스 태그 3개를 복습하고 문제를 풉니다.",
        "quest_type": "tag_review",
        "target": 3,
        "module_types": ["curriculum_group", "problem_solve"],
    },
    {
        "template_key": "hard_formula_mix",
        "difficulty": "hard",
        "title": "공식 혼합 문제 5문항",
        "description": "둘 이상의 공식을 함께 쓰는 문제 5문항을 풉니다.",
        "quest_type": "formula_apply",
        "target": 5,
        "module_types": ["problem_solve", "exam_solve"],
    },
    {
        "template_key": "hard_exam_2_accuracy",
        "difficulty": "hard",
        "title": "테스트 2회 평균 85%",
        "description": "미니 테스트 2회의 평균 정확도 85% 이상을 달성합니다.",
        "quest_type": "exam_average_accuracy",
        "target": 85,
        "module_types": ["exam_solve", "level_test"],
    },
    {
        "template_key": "hard_retry_7",
        "difficulty": "hard",
        "title": "재도전 7문항 정답",
        "description": "틀린 문제를 재도전해 7문항을 맞힙니다.",
        "quest_type": "retry_correct",
        "target": 7,
        "module_types": ["wrong_answer_review", "problem_solve"],
    },
    {
        "template_key": "hard_bundle_2",
        "difficulty": "hard",
        "title": "학습 묶음 2개 완료",
        "description": "오늘 배정된 학습 묶음 2개를 끝냅니다.",
        "quest_type": "bundle_complete",
        "target": 2,
        "module_types": ["curriculum_group", "challenge_group"],
    },
    {
        "template_key": "hard_final_push",
        "difficulty": "hard",
        "title": "오늘 최종 점검 완료",
        "description": "교재, 문제, 복습 중 3개 활동을 모두 완료합니다.",
        "quest_type": "final_check_complete",
        "target": 3,
        "module_types": ["textbook_view", "problem_solve", "wrong_answer_review"],
    },
]
